USE [master]
GO

/****** Object:  Database [topcar]    Script Date: 11/10/2020 12:32:50 PM ******/
CREATE DATABASE [topcar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TOPCAR', FILENAME = N'F:\sqldata\topcar.mdf' , SIZE = 1252800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'TOPCAR_log', FILENAME = N'E:\sqldata\topcar.ldf' , SIZE = 1014528KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [topcar] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [topcar].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [topcar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [topcar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [topcar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [topcar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [topcar] SET ARITHABORT OFF 
GO

ALTER DATABASE [topcar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [topcar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [topcar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [topcar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [topcar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [topcar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [topcar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [topcar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [topcar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [topcar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [topcar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [topcar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [topcar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [topcar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [topcar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [topcar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [topcar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [topcar] SET RECOVERY FULL 
GO

ALTER DATABASE [topcar] SET  MULTI_USER 
GO

ALTER DATABASE [topcar] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [topcar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [topcar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [topcar] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [topcar] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [topcar] SET QUERY_STORE = OFF
GO

USE [topcar]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [topcar] SET  READ_WRITE 
GO

